Removed deprecated call to require.paths.
Full error:

   Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:381:11)
    at Object.<anonymous> (/Users/m/repos/rabbitmq-service-nodejs-sample/app.js:1:70)
    at Module._compile (module.js:444:26)
    at Object..js (module.js:462:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.0 (module.js:482:10)
    at EventEmitter._tickCallback (node.js:192:40)